module.exports = [
    {
        submitter: "hnvss",
        monitor: "LG 49WL95C",
        mount: "Ergotron HX Single Ultrawide",
        speakers: "Audioengine A2+",
        keyboard: "Keychron K2",
        mouse: "Logitech MX Master 3, Apple Magic Trackpad 2",
        image: "https://i.redd.it/ssrdl8vh91971.jpg",
    },
    // {
    //     submitter: "No_Wedding_6186",
    //     monitor: "Samsung Odyssey G9",
    //     mount: "VIVO 17 to 43 inch Aluminum",
    //     speakers: "",
    //     keyboard: "Logitech G915 TKL",
    //     mouse: "Logitech G502 Lightspeed",
    //     image: "https://i.redd.it/ak6c3l3ojfl31.jpg",
    // },
    // {
    //     submitter: "ulresch",
    //     monitor: "LG 35WN73A-B",
    //     mount: "",
    //     speakers: "Edifier R1280DB",
    //     keyboard: "Logitech MX Keys",
    //     mouse: "Logitech MX Master 3",
    //     image: "https://i.redd.it/9so2uih9t1j81.jpg",
    // },
    // {
    //     submitter: "pradalaskan",
    //     monitor: "Acer Predator Z35p, Alienware AW3418DW, Acer Predator XB271HK",
    //     mount: "VIVO Premium Single Heavy Duty, VIVO Single Extra Tall",
    //     speakers: "Kef LS50 Wireless",
    //     keyboard: "Razer Huntsman Elite",
    //     mouse: "Finalmouse Air58",
    //     image: "https://i.imgur.com/SekRb37.jpeg",
    // },
    // {
    //     submitter: "superstrm",
    //     monitor: "Acer Predator X34P",
    //     mount: "RICOO S3111 Monitor Bracket",
    //     speakers: "Bowers & Wilkins MM-1",
    //     keyboard: "Cooler Master MasterKeys Pro L",
    //     mouse: "Logitech MX Master 3",
    //     image: "https://i.redd.it/jvx10jssm6s41.jpg",
    // },
    // {
    //     submitter: "PC_Battlestations",
    //     monitor: "LG 34GK950F-B",
    //     mount: "VideoSecu TV Wall Mount Articulating Arm",
    //     speakers: "Bose Companion",
    //     keyboard: "GMMK Compact 60%",
    //     mouse: "Glorious Model O",
    //     image: "https://i.redd.it/1gkp6jo1b3j41.jpg",
    // },
    // {
    //     submitter: "sleepywolf_",
    //     monitor: "Lenovo G34W-10",
    //     mount: "Amazon Basics Articulating Wall Mount",
    //     speakers: "Audioengine A2+",
    //     keyboard: "Logitech G915 TKL",
    //     mouse: "Redragon Perdition m901",
    //     image: "https://i.redd.it/ai46ucvfore51.jpg",
    // },
    // {
    //     submitter: "deselected",
    //     monitor: "Blaupunkt 75”, Blaupunkt 75”",
    //     mount: "Artiss TV Stand",
    //     speakers: "JBL LSR305 Studio Monitors",
    //     keyboard: "Microsoft Designer Compact",
    //     mouse: "Logitech MX Ergo Trackball",
    //     image: "https://i.redd.it/q740slomtmp81.jpg",
    // }
];


// Template
// {
//     submitter: "",
//     monitor: "",
//     mount: "",
//     speakers: "",
//     keyboard: "",
//     mouse: "",
//     image: "",
// },